const messages = {
  en: {
    'index.overline': 'Graphic Design • Motion Graphic Design',
    'index.footer': 'Made with ❤️ in Canada',
    'lang.en': 'English',
    'lang.hu': 'Hungarian',
    'lang.it': 'Italian',
    'index.contact': 'Contact',
    'index.email': 'Email',
    'index.phone': 'Phone',
    'index.message': 'Message',
    'index.send': 'Send',
    'index.sent': 'Sent',
    'index.name': 'Name',
    'index.send-message': 'Send a message',
    'projects.bari.title': 'Hairdresser logo',
    'projects.books-teens.title': 'Book cover design',
    'projects.cctv.title': 'CCTV-time lapse logo',
    'projects.cctv.description': 'I did this project for a start-up company, that was developing a system for construction sites. They installed CCTV cameras on the construction ground and did a time lapse of the entire construction from start to finish.',
    'projects.ef-studio.title': 'EF studio',
    'projects.ef-studio.description': 'Logo for video company',
    'projects.fruit-pattern.title': 'Fruit pattern design',
    'projects.fruit-pattern.description': 'I made this pattern design for a company that sells breakfast cereals',
    'projects.koncz.title': 'Photographer logo',
    'projects.koncz.description': 'This logo is for a freelance photographer named Koncz',
    'projects.landscape.title': 'Nighttime Landscape',
    'projects.landscape.description': `For Easter 2020 I was assigned to make a design based on the fact that we can't celebrate Jesus's resurrection the same way as we used to. At this time, when a hug becomes a weapon and staying away from your family is an act of love, it's important to see that little thing we can still be thankful for. I hope this design makes you wonder a little, about these things!`,
    'projects.lumiere.title': 'Lumière',
    'projects.lumiere.description': 'Lumière - French for "Light"',
    'projects.scout.title': 'Hungarian Scout clothing design',
    'projects.scout.description': 'My job in this project was to create a design for a T-shirt and a scouts-tie for Hungarian scouts, who will attend international events. My reference for pattern on the scouts-tie was traditional Hungarian sewing pattern. All the elements of the T-shirt design are either a scout or a Hungarian symbol.',
    'projects.history-animation.title': 'Néri History Animation',
    'projects.mtv-intro.title': 'Néri MTV Intro Animation',
  },
  hu: {
    'index.overline': 'Grafikai Tervezés • Animáció Készítés',
    'index.footer': '❤️ Szeretettel készült Kanadában',
    'lang.en': 'Angol',
    'lang.hu': 'Magyar',
    'lang.it': 'Olasz',
    'index.contact': 'Kapcsolat',
    'index.email': 'E-mail',
    'index.phone': 'Telefon',
    'index.message': 'Üzenet',
    'index.send': 'Küldés',
    'index.sent': 'Elküldve',
    'index.name': 'Név',
    'index.send-message': 'Üzenet küldése',
    'projects.bari.title': 'Fodrász logó',
    'projects.books-teens.title': 'Könyvborító kialakítása',
    'projects.cctv.title': 'CCTV-time lapse logo',
    'projects.cctv.description': `Ezt a projektet egy induló vállalkozásnak készítettem, amely az építkezések kamerarendszerét fejlesztette ki. CCTV kamerákat szereltek fel az építkezésen, és timelapse-et készített az egész építkezésről az elejétől a végéig.`,
    'projects.ef-studio.title': 'EF studio',
    "projects.ef-studio.description": "Videótársaság logója",
    'projects.fruit-pattern.title': 'Gyümölcsminta kialakítása',
    "projects.fruit-pattern.description": "Ezt a mintát egy reggeli müzlit forgalmazó vállalatnak készítettem",
    'projects.koncz.title': 'Fotós logó',
    'projects.koncz.description': 'Ez a logó egy Koncz nevű szabadúszó fotósnak készült',
    "projects.landscape.title": "Éjszakai táj",
    'projects.landscape.description': `2020 húsvétjára megbízást kaptam arra, hogy elkészítsek egy tervet, amely azon a tényen alapul, hogy Jézus feltámadását nem ugyanúgy ünnepelhetjük, mint korábban. Ebben az időben, amikor az ölelés fegyverré válik, és a családjától való távolmaradás szeretetet jelent, fontos látnunk azt a kis dolgot, amiért még mindig hálásak lehetünk. Remélem, hogy ez a kialakítás segít egy kicsit elgondolkozni ezeken a dolgokon!`,
    'projects.lumiere.title': 'Lumière',
    "projects.lumiere.description": `Lumière - franciául "Fény"`,
    'projects.scout.title': 'Magyar cserkész ruházattervezés',
    'projects.scout.description': 'Az én feladatom ebben a projektben az volt, hogy elkészítsek egy pólót és egy cserkész-nyakkendőt magyar cserkészeknek, akik részt vesznek nemzetközi eseményeken. A cserkész-nyakkendő mintájára a hagyományos magyar varrásmintát használtam. A póló minden eleme cserkész vagy magyar szimbólum.',
    'projects.history-animation.title': 'Néri History Animation',
    'projects.mtv-intro.title': 'Néri MTV Intro Animation',
  },
  it: {
    'index.overline': 'Progettazione grafica • Animazioni',
    'index.footer': 'Realizzato con ❤️ in Canada',
    'lang.en': 'Inglese',
    'lang.hu': 'Ungherese',
    'lang.it': 'Italiano',
    'index.contact': 'Contatto',
    'index.email': 'Email',
    'index.phone': 'Telefono',
    'index.message': 'Messaggio',
    'index.send': 'Invia',
    'index.sent': 'Inviato',
    'index.name': 'Nome',
    'index.send-message': 'Invia un messaggio',
    'projects.bari.title': 'Parrucchiere logo',
    'projects.books-teens.title': 'Design copertina del libro',
    "projects.cctv.title": "CCTV-time lapse logo",
    'projects.cctv.description': `Ho fatto questo progetto per una start-up, che stava sviluppando un sistema per i cantieri. Hanno installato telecamere a circuito chiuso sul terreno di costruzione e hanno fatto un timelapse dell'intera costruzione dall'inizio alla fine.`,
    'projects.ef-studio.title': 'EF studio',
    'projects.ef-studio.description': 'Logo per società di video',
    'projects.fruit-pattern.title': 'Fruit pattern design',
    'projects.fruit-pattern.description': `Ho realizzato questo motivo per un'azienda che vende cereali per la colazione`,
    'projects.koncz.title': "Fotografo logo",
    "projects.koncz.description": "Questo logo è per un fotografo freelance di nome Koncz",
    'projects.landscape.title': 'Paesaggio notturno',
    'projects.landscape.description': `Per Pasqua 2020 mi è stato assegnato il compito di realizzare un progetto basato sul fatto che non possiamo celebrare la risurrezione di Gesù nello stesso modo in cui facevamo prima. In questo momento, quando un abbraccio diventa un'arma e stare lontano dalla tua famiglia è un atto d'amore, è importante vedere quella piccola cosa di cui possiamo ancora essere grati. Spero che questo design ti faccia riflettere un po 'su queste cose! `,
    'projects.lumiere.title': 'Lumière',
    'projects.lumiere.description': 'Lumière - "Luce" in francese',
    'projects.scout.title': 'Design di abbigliamento scout ungherese',
    'projects.scout.description': 'Il mio lavoro in questo progetto era creare un disegno per una maglietta e una cravatta scout per gli scout ungheresi, che parteciperanno a eventi internazionali. Il mio riferimento per il modello sulla cravatta da scout era il tradizionale modello di cucito ungherese. Tutti gli elementi del design della maglietta sono uno scout o un simbolo ungherese. ',
    'projects.history-animation.title': 'Néri History Animation',
    'projects.mtv-intro.title': 'Néri MTV Intro Animation',
  }
}

export type supported = keyof typeof messages;
export const languages = Object.keys(messages) as supported[];
export const defaultLang: supported = "en";
export type messageKey = keyof typeof messages.en;

export function t(key: messageKey, tag: supported): string {
  return messages[tag][key];
}